<#
.SYNOPSIS
    Interactive .env file creator for MasstTrader.
.DESCRIPTION
    Prompts for each environment variable and writes a .env file.
    Run this after setup.ps1, before starting the service.
#>

$INSTALL_DIR = "C:\masstTrader"
$ENV_FILE = "$INSTALL_DIR\.env"

if (-not (Test-Path $INSTALL_DIR)) {
    Write-Error "MasstTrader not found at $INSTALL_DIR. Run setup.ps1 first."
    exit 1
}

Write-Host ""
Write-Host "MasstTrader .env Configuration" -ForegroundColor Cyan
Write-Host "==============================" -ForegroundColor Cyan
Write-Host "Press Enter to skip optional fields (defaults shown in brackets)."
Write-Host ""

# Load existing .env values if file exists
$existing = @{}
if (Test-Path $ENV_FILE) {
    Write-Host "Found existing .env - current values will be shown as defaults." -ForegroundColor Yellow
    Get-Content $ENV_FILE | ForEach-Object {
        if ($_ -match "^([^#=]+)=(.*)$") {
            $existing[$Matches[1].Trim()] = $Matches[2].Trim()
        }
    }
}

function Prompt-Value {
    param(
        [string]$Name,
        [string]$Description,
        [string]$Default = "",
        [bool]$Required = $false,
        [bool]$IsSecret = $false
    )
    $existingVal = $existing[$Name]
    $displayDefault = if ($existingVal) { $existingVal } else { $Default }

    if ($IsSecret -and $existingVal) {
        $masked = $existingVal.Substring(0, [Math]::Min(4, $existingVal.Length)) + "****"
        $displayDefault = $masked
    }

    $prompt = "  $Name"
    if ($Description) { $prompt += " ($Description)" }
    if ($displayDefault) { $prompt += " [$displayDefault]" }
    if ($Required) { $prompt += " *REQUIRED*" }
    $prompt += ": "

    $value = Read-Host $prompt
    if ([string]::IsNullOrWhiteSpace($value)) {
        $value = if ($existingVal) { $existingVal } else { $Default }
    }

    if ($Required -and [string]::IsNullOrWhiteSpace($value)) {
        Write-Host "    This field is required!" -ForegroundColor Red
        return Prompt-Value -Name $Name -Description $Description -Default $Default -Required $Required -IsSecret $IsSecret
    }

    return $value
}

Write-Host "-- MT5 Connection --" -ForegroundColor Yellow
$mt5Login = Prompt-Value -Name "MT5_LOGIN" -Description "MT5 account number" -Required $false
$mt5Password = Prompt-Value -Name "MT5_PASSWORD" -Description "MT5 password" -IsSecret $true -Required $false
$mt5Server = Prompt-Value -Name "MT5_SERVER" -Description "Broker server" -Default "Exness-MT5Trial15" -Required $false
$mt5Path = Prompt-Value -Name "MT5_PATH" -Description "Path to terminal64.exe, leave empty for default" -Required $false

Write-Host ""
Write-Host "-- AI Provider --" -ForegroundColor Yellow
$aiProvider = Prompt-Value -Name "AI_PROVIDER" -Description "groq, google, anthropic, openai" -Default "groq" -Required $true
$groqKey = Prompt-Value -Name "GROQ_API_KEY" -Description "Groq API key" -IsSecret $true -Required $false
$groqModel = Prompt-Value -Name "GROQ_MODEL" -Description "Groq model id (llama-3.3-70b-versatile is decommissioned)" -Default "openai/gpt-oss-120b" -Required $false
$googleKey = Prompt-Value -Name "GOOGLE_API_KEY" -Description "Google Gemini key" -IsSecret $true -Required $false
$anthropicKey = Prompt-Value -Name "ANTHROPIC_API_KEY" -Description "Anthropic key" -IsSecret $true -Required $false
$openaiKey = Prompt-Value -Name "OPENAI_API_KEY" -Description "OpenAI key" -IsSecret $true -Required $false

Write-Host ""
Write-Host "-- V2 Autonomous Agent --" -ForegroundColor Yellow
$agentEnv = Prompt-Value -Name "AGENT_ENV" -Description "demo (paper) or live (REAL MONEY)" -Default "demo" -Required $true
$tfMode = Prompt-Value -Name "TF_MODE" -Description "scalping, intraday, swing, daily" -Default "intraday" -Required $false
$watchlist = Prompt-Value -Name "WATCHLIST" -Description "comma-separated symbols" -Default "XAUUSDm,BTCUSDm" -Required $false
$loopInterval = Prompt-Value -Name "LOOP_INTERVAL_SECONDS" -Description "seconds between agent cycles" -Default "300" -Required $false
$cryptoTestnet = Prompt-Value -Name "CRYPTO_TESTNET" -Description "true or false" -Default "true" -Required $false

if ($agentEnv -eq "live") {
    Write-Host ""
    Write-Host "  WARNING: AGENT_ENV=live places REAL orders on your broker account." -ForegroundColor Red
    $confirm = Read-Host "  Type LIVE to confirm, anything else reverts to demo"
    if ($confirm -ne "LIVE") { $agentEnv = "demo"; Write-Host "  Reverted to demo." -ForegroundColor Yellow }
}

Write-Host ""
Write-Host "-- Security --" -ForegroundColor Yellow
$apiKey = Prompt-Value -Name "API_KEY" -Description "API authentication key, leave empty to disable" -Required $false
$corsOrigins = Prompt-Value -Name "CORS_ORIGINS" -Description "Allowed origins, comma-separated" -Default "http://localhost:3000" -Required $false

# Write .env file
$envContent = @"
# MasstTrader Environment Configuration
# Generated by env-template.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# MT5 Connection
MT5_LOGIN=$mt5Login
MT5_PASSWORD=$mt5Password
MT5_SERVER=$mt5Server
MT5_PATH=$mt5Path

# AI Provider
AI_PROVIDER=$aiProvider
GROQ_API_KEY=$groqKey
GROQ_MODEL=$groqModel
GOOGLE_API_KEY=$googleKey
ANTHROPIC_API_KEY=$anthropicKey
OPENAI_API_KEY=$openaiKey

# Security
API_KEY=$apiKey
CORS_ORIGINS=$corsOrigins

# V2 Autonomous Agent
AGENT_ENV=$agentEnv
TF_MODE=$tfMode
WATCHLIST=$watchlist
LOOP_INTERVAL_SECONDS=$loopInterval
CRYPTO_TESTNET=$cryptoTestnet
"@

Set-Content -Path $ENV_FILE -Value $envContent -Encoding UTF8

Write-Host ""
Write-Host ".env written to $ENV_FILE" -ForegroundColor Green
Write-Host ""
Write-Host "Now restart the service:" -ForegroundColor Yellow
Write-Host "  nssm restart massttrader"
Write-Host ""
